<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/Pandaslearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Owen Harris", "Henry", "Elizabeth", "Mickey"],
    "Age": [22, 35, 58, 22],
    "Gender": ["male", "male", "female", "male"]
})

df

          Name  Age  Gender
0  Owen Harris   22    male
1        Henry   35    male
2    Elizabeth   58  female
3       Mickey   22    male

In [2]:
emp = pd.read_csv("employee.csv")

emp.head()

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [3]:
 (
emp.loc[emp["department"] == "IT", ["name", "salary","department"]]
.sort_values(by = "salary", ascending = False)
.nlargest(3, "salary")
)

            name    salary department
40  Raj Malhotra  110000.0         IT
16   Sameer Khan   91000.0         IT
36   Sameer Khan   91000.0         IT

In [ ]:
#Find employees who work in IT OR Finance

emp[(emp["department"] == "IT") | (emp["department"] == "Finance")]

In [ ]:
#2.	Find employees who are from Hyderabad or Bangalore AND have a salary above 60,000

emp.loc[((emp["city"] == "Hyderabad") | (emp["city"] == "Bangalore")) & (emp["salary"] > 60000)]

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
6,107,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0
7,108,Sneha Rao,28.0,HR,Bangalore,61000.0,4.0,2020-09-14,3.0
16,117,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0
21,122,Priya Reddy,NaN,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
26,127,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0
27,128,Sneha Rao,28.0,HR,Bangalore,61000.0,4.0,2020-09-14,3.0
36,137,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0

In [ ]:
'''
3.	Find employees who have:
	More than 5 years of experience
	Performance rating >= 4
	Salary > 70,000

'''

(
    emp.loc
    [
        (emp["experience_years"] > 5.0) &
        (emp["performance_rating"] >= 4) &
        (emp["salary"] > 70000),
        ["employee_id", "name", "salary"]

    ]
)

    employee_id           name    salary
2           103    Rahul Kumar   75000.0
4           105   Vikram Patel   82000.0
6           107    Arjun Mehta   72000.0
8           109    Rohan Gupta   95000.0
10          111     Karan Shah   79000.0
14          115   Manish Yadav   85000.0
16          117    Sameer Khan   91000.0
18          119  Nikhil Bansal   78000.0
24          125   Vikram Patel   82000.0
26          127    Arjun Mehta   72000.0
28          129    Rohan Gupta   95000.0
30          131     Karan Shah   79000.0
34          135   Manish Yadav   85000.0
36          137    Sameer Khan   91000.0
38          139  Nikhil Bansal   78000.0
40          141   Raj Malhotra  110000.0
42          143    Dev Agarwal   88000.0
46          147    Akash Sinha   92000.0
48          149   Varun Kapoor   81000.0

In [ ]:
#4.	Find employees whose salary is between 60,000 and 80,000, inclusive.

emp[emp["salary"].between(60000, 80000)]

In [8]:
#5.	Find employees whose name starts with "A".

emp[emp["name"].str.startswith("A")][["employee_id", "name"]]

emp.loc[emp["name"].str.startswith("A"), ["employee_id", "name","department"]]

    employee_id          name department
0           101  Aarav Sharma         IT
3           104  Ananya Singh         IT
6           107   Arjun Mehta         IT
12          113  Aditya Joshi    Finance
20          121  Aarav Sharma         IT
23          124  Ananya Singh         IT
26          127   Arjun Mehta         IT
32          133  Aditya Joshi    Finance
46          147   Akash Sinha    Finance

In [ ]:
#6.	Find employees whose name contains the letter "a", regardless of capitalization.

emp.loc[emp["name"].str.contains("a", case = False), ["employee_id", "name"]]

In [20]:
#9.	Using .loc[], increase the salary of all IT employees by 10%.
# assign function does not modify original df. it creates a new df

emp.loc[emp["department"] == "IT", ["name","salary"]].assign(new_salary = lambda x : x["salary"] * (110/100))

            name    salary  new_salary
0   Aarav Sharma   55000.0     60500.0
3   Ananya Singh   68000.0     74800.0
6    Arjun Mehta   72000.0     79200.0
11    Meera Iyer   70000.0     77000.0
16   Sameer Khan   91000.0    100100.0
20  Aarav Sharma   55000.0     60500.0
23  Ananya Singh   68000.0     74800.0
26   Arjun Mehta   72000.0     79200.0
31    Meera Iyer   70000.0     77000.0
36   Sameer Khan   91000.0    100100.0
40  Raj Malhotra  110000.0    121000.0
45  Nandini Bose   66000.0     72600.0

In [25]:
#10. Change the performance rating of employees with salary greater than 90,000 to 5.

#emp.loc[emp["salary"] > 90000, "performance_rating"] = 5

emp[emp["salary"] > 90000]

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
8,109,Rohan Gupta,40.0,Finance,Mumbai,95000.0,15.0,2010-02-18,5.0
16,117,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0
28,129,Rohan Gupta,40.0,Finance,Mumbai,95000.0,15.0,2010-02-18,5.0
36,137,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0
40,141,Raj Malhotra,45.0,IT,Delhi,110000.0,20.0,2005-02-14,5.0
46,147,Akash Sinha,39.0,Finance,Patna,92000.0,14.0,2011-03-08,5.0

In [26]:
#SECTION 3 - VALUE_COUNTS()

#11. Find how many employees belong to each department.

emp["department"].value_counts()

department
IT           12
Finance      10
Sales        10
Marketing    10
HR            8
Name: count, dtype: int64

In [34]:
#14. Find the percentage of employees belonging to each department.

emp["department"].value_counts(normalize=True) * 100

department
IT           24.0
Finance      20.0
Sales        20.0
Marketing    20.0
HR           16.0
Name: proportion, dtype: float64