<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/PandasLvL3/PandasLvL3Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS LEVEL 3 - PRACTICE QUESTIONS**

In [4]:
import pandas as pd

emp = pd.read_csv("employee.csv")
dept = pd.read_csv("department.csv")

emp.head()

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [3]:
dept.head()

  department       manager   location   budget
0         IT  Raj Malhotra  Hyderabad  5000000
1         HR   Priya Reddy  Hyderabad  2500000
2    Finance   Rahul Kumar  Bangalore  4000000
3      Sales  Vikram Patel     Mumbai  4500000
4  Marketing    Neha Verma      Delhi  3000000

In [ ]:
#2.	Merge employees and departments using the department column.

m = pd.merge(emp, dept, on = "department", how = "inner")

m[["name", "department","manager", "location"]]

In [ ]:
#5.	Find employees who work in the same city as their department location.

m.loc[m["city"] == m["location"], ["name", "city", "location"]]

In [22]:
#7.	After merging, find the average salary for each manager.

m.groupby("manager")["salary"].mean()

manager
Neha Verma      56500.000000
Priya Reddy     58500.000000
Rahul Kumar     81222.222222
Raj Malhotra    74000.000000
Vikram Patel    77800.000000
Name: salary, dtype: float64

In [45]:
#8.	Find the total number of employees managed by each manager.

m.groupby("manager")["employee_id"].count()

manager
Neha Verma      10
Priya Reddy      8
Rahul Kumar     10
Raj Malhotra    12
Vikram Patel    10
Name: employee_id, dtype: int64

In [54]:
#9.	Find the highest-paid employee under each manager.

result = (
    m.loc[
        m.groupby("manager")["salary"].idxmax(),
        ["salary", "name", "manager"]
    ]
)

result

      salary          name       manager
43   63000.0  Kavya Pillai    Neha Verma
1    62000.0   Priya Reddy   Priya Reddy
8    95000.0   Rohan Gupta   Rahul Kumar
40  110000.0  Raj Malhotra  Raj Malhotra
14   85000.0  Manish Yadav  Vikram Patel

In [62]:
#10.	Find the average salary of employees in each department along with the department budget.

m.groupby("department")[["salary", "budget"]].mean()

                  salary     budget
department
Finance     81222.222222  4000000.0
HR          58500.000000  2500000.0
IT          74000.000000  5000000.0
Marketing   56500.000000  3000000.0
Sales       77800.000000  4500000.0

In [63]:
dept

  department       manager   location   budget
0         IT  Raj Malhotra  Hyderabad  5000000
1         HR   Priya Reddy  Hyderabad  2500000
2    Finance   Rahul Kumar  Bangalore  4000000
3      Sales  Vikram Patel     Mumbai  4500000
4  Marketing    Neha Verma      Delhi  3000000